name: Practice
api: ["3.0.0"]
version: "2.0.0"
main: jkorn\practice\PracticeCore
description: "Practice - by jkorn2324"
website: "https://github.com/jkorn2324"

permissions:
  practice.permission.manage.kits:
    description: "Allows the player to manage the kits."
    default: op
  practice.permission.spectate:
    description: "Allows the player to spectate other games."
    default: true
  practice.permission.manage.arenas:
    description: "Allows the player to manage the arenas."
    default: op